version: 0.2

phases:
  install:
    commands:
      - cd app
      - npm install
  build:
    commands:
      - npm run build
      - ls -l
      - ls -l dist
      - cd ..
artifacts:
  files:
    - appspec.yml
    - app/**/*
